title: Aderson JORDAN 
description: A minimal and beautiful Jekyll theme best for writing and note-taking.
author: FUUGUII
avatar: /logo.png
email: DFYTY@GMAIL.COM

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - LEER
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ANDJOE
  card: sHIHO
logo: IUGB
social:
  name: BKHBKBNNKNKK,
  links:
    - WWW.CEDCCSC.COM
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
